# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b13361e57f52819a42c3385c1fb6319c5082aa05aa3536b932f0886f8df76756ed3b15bb64ef73a48d14d70bb406639609f76c63c4f76c02f4e0241df5744781

test:
  secret_key_base: 6777fd6c132b8f89edc4adc7db2eacfb5d2dcb87bb52556b15c1b5831ca0bf12c814939c4dc271a1b384f0d77da3d50a10412260b635b5eaed9660717c4c183d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
